### ISSUE TITLE
Gold spammers inviting people to raids to spam in /raidwarning. Block invites based on lvl?

### ISSUE THREAD

**Issue by dogmax** [fjaros/IgnoreLevel-2.4.3#10]
Title

**Description of problem:** Gold spammers are now inviting people to raid groups to spam advertisements in raid warnings. This is drastically more spammy. Besides actual gold spam, the chat is flooded with "has left" or "has joined" yellow messages as well. 

Furthermore, it's normal to get a random invite while questing. The invitation itself is also incredibly annoying.

**Suggestion:** Also block group invites from players based on lvl.

**Comment by fjaros** [comment]
Implemented in https://github.com/fjaros/IgnoreLevel-2.4.3/commit/85b4226e1750547f59710d4aeddc8c6040657f36
