### ISSUE TITLE
ElvUI incompatibility

### ISSUE THREAD

**Issue by fjaros** [fjaros/IgnoreLevel-2.4.3#11]
Got this problem after last update...

https://www.dropbox.com/s/ei2hlstjobuqkr1/double%20whisp.JPG?dl=0
https://www.dropbox.com/s/9l1nuk9my3qnr55/elvui%20ignorelevel.txt?dl=0

_Originally posted by @T0mken in https://github.com/fjaros/IgnoreLevel-2.4.3/issues/2#issuecomment-462138132_

**Comment by fjaros** [comment]
@T0mken, when is the last time you updated ElvUI? The lua script for ElvUI has changed so I can't see exactly where in ElvUI it fails 2) Does this happen all the time or just sometimes?

**Comment by T0mken** [comment]
@fjaros I downloaded the latest ElvUI version from [here](https://github.com/ElvUI-TBC/ElvUI) after this happen, I also deleted ignorelevel files in WTF and addon before addin it again.
I also got an error when I tried to equip a new weapon (I can't equip with ignorelevel addon enable)
https://i.imgur.com/wkfTha7.jpg

I will try a bit different things tomorrow to see if there is anything else that could be the main problem.

**Comment by fjaros** [comment]
thanks. i know about the equip item problem - there is some problem with ElvUI popup window and the way the addon tries to block party invites from bots. i'll work on this as well.

**Comment by fjaros** [comment]
Fix committed in https://github.com/fjaros/IgnoreLevel-2.4.3/commit/eafdd014659292b1d64182ee25785f4b59a2a35f . Please try latest version.
