### ISSUE TITLE
All whispers ignored regardless of level

### ISSUE THREAD

**Issue by Lebaowski** [fjaros/IgnoreLevel-2.4.3#4]
Whenever someone whispers me their /who result shows up but no whisper even if the player is level 26 and the addon is set to it's default value. I've tried disabling all other addons besides 'Addon Control Panel', issue is still present.

Some whispers seem to get through, no idea what the criteria is but it's never the first attempt by any given character to whisper, when LFM for a dungeon last night a guy told me he whispered me 3 times before I responded, but only his 3rd whisper actually came through to me. When testing this on my alt account I couldn't get it to go through no matter how many times I tried.

Playing on Netherwing.

**Comment by fjaros** [comment]
Are you using ElvUI? This might be a side effect of having chat history turned on in ElvUI. I'm working on ways to make the addon more compatible with this.

**Comment by Lebaowski** [comment]
Yes been using ElvUI. How come the issue persist even though the whole addon, and every other addon is turned off? Do I need to restart the client?

**Comment by fjaros** [comment]
Please try the new version and let me know

**Comment by Lebaowski** [comment]
It now works from my level 43 to my level 26, but not from my 26 to my 43. I think it might have to do with the 26 having a short name, and returning several results when /who is used so the addon doesn't know which of them sent the whisper. Blocks the gold spam though, I can live without people with short names in my dungeons for a little while.

Thanks for you work!

Edit: /who list also keeps popping up after closing it when whispered by a character with a name which returns several results as if it keeps trying to find the level of the character who tried to whisper me. Continues after relog/reload, addon has to be disabled for it to stop.

**Comment by fjaros** [comment]
yeah that absolutely makes sense with the short names. thanks for the hint! i'll try to figure something out for this. i might have to hook the who list window instead of using the results returned in console (as that won't work for the short name case)

**Comment by fjaros** [comment]
I checked the server source. Unfortunately if your name is something like "Go" where the letters can be found inside of many other words, the server simply uses logic like:
start looking through all players
   if results < 50
      if (looked_at_player's name contains the name in who command)
          add_to_result(looked_at_player's name)
end loop

**Comment by fjaros** [comment]
one temporary workaround would be to make the addon ignore all short names, let's say 4 characters or fewer, and mark them automatically whitelisted. let me create that fix for you while i think about something more robust. you can download from this branch - https://github.com/fjaros/IgnoreLevel-2.4.3/tree/short_name_whitelist or alternatively edit the lua file manually. the change is very simple: https://github.com/fjaros/IgnoreLevel-2.4.3/commit/ec6faddaed19aedaa9c0b63643464178e100401f

**Comment by Lebaowski** [comment]
Works great! Haven't seen any spammers with 4 letter or shorter names so far, lets hope they don't adapt!

Thank you again, really appreciate your work to get it working with ElvUI and the continued support :)

**Comment by fjaros** [comment]
Great! Closing this. Opened issue https://github.com/fjaros/IgnoreLevel-2.4.3/issues/5 to track better short name support.
