### ISSUE TITLE
Does not work with very short character names

### ISSUE THREAD

**Issue by fjaros** [fjaros/IgnoreLevel-2.4.3#5]
Short character names which could potentially be found inside of other words like "Go" make the who command spawn the who window and ignore the result completely. Need to implement hooking for who window to allow for this case.
Stop gap is to automatically whitelist all < 5 name length character names: https://github.com/fjaros/IgnoreLevel-2.4.3/tree/short_name_whitelist

**Comment by ghost** [comment]
Had to disable the addon because of this.

**Comment by fjaros** [comment]
The addon (newer versions) automatically whitelists all names that are 2-3 characters.
